//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PenaltyCalculation.Models.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PenaltyCalculateDBEntities1 : DbContext
    {
        public PenaltyCalculateDBEntities1()
            : base("name=PenaltyCalculateDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<Holiday> Holiday { get; set; }
    
        public virtual ObjectResult<spFindingHoliday_Result> spFindingHoliday(string datefirst, string datelast, Nullable<int> fkCountry)
        {
            var datefirstParameter = datefirst != null ?
                new ObjectParameter("datefirst", datefirst) :
                new ObjectParameter("datefirst", typeof(string));
    
            var datelastParameter = datelast != null ?
                new ObjectParameter("datelast", datelast) :
                new ObjectParameter("datelast", typeof(string));
    
            var fkCountryParameter = fkCountry.HasValue ?
                new ObjectParameter("fkCountry", fkCountry) :
                new ObjectParameter("fkCountry", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spFindingHoliday_Result>("spFindingHoliday", datefirstParameter, datelastParameter, fkCountryParameter);
        }
    }
}
